package com.rashik.rashikmart.dao;

import com.rashik.rashikmart.config.DatabaseConfig;
import com.rashik.rashikmart.model.CartItem;
import com.rashik.rashikmart.model.Product;
import com.rashik.rashikmart.model.User;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;

public class CartDAOTest {

    private static UserDAO userDAO;
    private static ProductDAO productDAO;
    private static CartDAO cartDAO;
    private static User seller;
    private static User buyer;

    @BeforeClass
    public static void setUp() throws Exception {
        userDAO = new UserDAO();
        productDAO = new ProductDAO();
        cartDAO = new CartDAO();

        try (Connection conn = DatabaseConfig.getDataSource().getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS users (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        email VARCHAR(150) NOT NULL UNIQUE,
                        password VARCHAR(255) NOT NULL,
                        role VARCHAR(30) NOT NULL
                    );
                    CREATE TABLE IF NOT EXISTS products (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        seller_id INT NOT NULL,
                        name VARCHAR(150) NOT NULL,
                        description VARCHAR(1000),
                        category VARCHAR(100) NOT NULL,
                        price DECIMAL(12,2) NOT NULL,
                        quantity INT NOT NULL,
                        image_url VARCHAR(255) DEFAULT 'default-product.svg',
                        active BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS cart (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        buyer_id INT NOT NULL UNIQUE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_cart_buyer FOREIGN KEY (buyer_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS cart_items (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        cart_id INT NOT NULL,
                        product_id INT NOT NULL,
                        quantity INT NOT NULL,
                        CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
                        CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
                        CONSTRAINT uq_cart_product UNIQUE (cart_id, product_id)
                    );
                    """);
        }

        String prefix = UUID.randomUUID().toString().substring(0, 8);
        userDAO.registerUser(new User("Cart Seller", "cseller_" + prefix + "@test.com", "pass123", "SELLER"));
        userDAO.registerUser(new User("Cart Buyer", "cbuyer_" + prefix + "@test.com", "pass123", "BUYER"));
        seller = userDAO.findByEmail("cseller_" + prefix + "@test.com");
        buyer = userDAO.findByEmail("cbuyer_" + prefix + "@test.com");
    }

    @Test
    public void testAddAndAccumulateCartItems() {
        Product p = new Product(seller.getId(), "Cart Test Item", "desc", "Pantry", new BigDecimal("50.00"), 20);
        productDAO.addProduct(p);
        List<Product> prods = productDAO.findBySellerId(seller.getId());
        Product created = null;
        for (Product item : prods) {
            if ("Cart Test Item".equals(item.getName())) {
                created = item;
                break;
            }
        }
        Assert.assertNotNull(created);

        // Add 3 units
        boolean added = cartDAO.addItem(buyer.getId(), created.getId(), 3);
        Assert.assertTrue(added);

        List<CartItem> items = cartDAO.getCartItems(buyer.getId());
        CartItem cartItem = null;
        for (CartItem ci : items) {
            if (ci.getProductId() == created.getId()) {
                cartItem = ci;
                break;
            }
        }
        Assert.assertNotNull(cartItem);
        Assert.assertEquals(3, cartItem.getQuantity());

        // Add 2 more units (accumulates to 5)
        boolean addedMore = cartDAO.addItem(buyer.getId(), created.getId(), 2);
        Assert.assertTrue(addedMore);

        items = cartDAO.getCartItems(buyer.getId());
        for (CartItem ci : items) {
            if (ci.getProductId() == created.getId()) {
                cartItem = ci;
                break;
            }
        }
        Assert.assertEquals(5, cartItem.getQuantity());
        cartDAO.removeItem(buyer.getId(), created.getId());
    }

    @Test
    public void testAddBeyondStockFails() {
        Product p = new Product(seller.getId(), "Low Stock Item", "desc", "Produce", new BigDecimal("10.00"), 5);
        productDAO.addProduct(p);
        List<Product> prods = productDAO.findBySellerId(seller.getId());
        Product created = null;
        for (Product item : prods) {
            if ("Low Stock Item".equals(item.getName())) {
                created = item;
                break;
            }
        }
        Assert.assertNotNull(created);

        // Attempt to add 6 when only 5 exist
        boolean addedExcess = cartDAO.addItem(buyer.getId(), created.getId(), 6);
        Assert.assertFalse("Adding more than available stock should fail", addedExcess);

        // Invalid inputs
        Assert.assertFalse(cartDAO.addItem(-1, created.getId(), 1));
        Assert.assertFalse(cartDAO.addItem(buyer.getId(), -1, 1));
        Assert.assertFalse(cartDAO.addItem(buyer.getId(), created.getId(), 0));
        Assert.assertFalse(cartDAO.addItem(buyer.getId(), created.getId(), -5));
    }

    @Test
    public void testUpdateQuantityAndRemove() {
        Product p = new Product(seller.getId(), "Upd Item", "desc", "Snacks", new BigDecimal("30.00"), 10);
        productDAO.addProduct(p);
        List<Product> prods = productDAO.findBySellerId(seller.getId());
        Product created = null;
        for (Product item : prods) {
            if ("Upd Item".equals(item.getName())) {
                created = item;
                break;
            }
        }
        Assert.assertNotNull(created);

        cartDAO.addItem(buyer.getId(), created.getId(), 2);

        // Update quantity to 4
        boolean updated = cartDAO.updateQuantity(buyer.getId(), created.getId(), 4);
        Assert.assertTrue(updated);

        // Update beyond stock (15 > 10)
        boolean updateBeyond = cartDAO.updateQuantity(buyer.getId(), created.getId(), 15);
        Assert.assertFalse("Updating quantity beyond available stock should fail", updateBeyond);

        // Update to 0 should remove item
        boolean updateZero = cartDAO.updateQuantity(buyer.getId(), created.getId(), 0);
        Assert.assertTrue(updateZero);

        List<CartItem> items = cartDAO.getCartItems(buyer.getId());
        for (CartItem ci : items) {
            Assert.assertNotEquals(created.getId(), ci.getProductId());
        }

        // Direct removeItem
        cartDAO.addItem(buyer.getId(), created.getId(), 1);
        boolean removed = cartDAO.removeItem(buyer.getId(), created.getId());
        Assert.assertTrue(removed);
    }

    @Test
    public void testGetCartTotalAndClearCart() {
        Product p1 = new Product(seller.getId(), "Prod 1", "desc", "Produce", new BigDecimal("100.50"), 10);
        Product p2 = new Product(seller.getId(), "Prod 2", "desc", "Produce", new BigDecimal("25.25"), 10);
        productDAO.addProduct(p1);
        productDAO.addProduct(p2);

        List<Product> prods = productDAO.findBySellerId(seller.getId());
        Product item1 = null, item2 = null;
        for (Product p : prods) {
            if ("Prod 1".equals(p.getName())) item1 = p;
            if ("Prod 2".equals(p.getName())) item2 = p;
        }
        Assert.assertNotNull(item1);
        Assert.assertNotNull(item2);

        cartDAO.clearCart(buyer.getId());
        Assert.assertEquals(BigDecimal.ZERO, cartDAO.getCartTotal(buyer.getId()));

        cartDAO.addItem(buyer.getId(), item1.getId(), 2); // 201.00
        cartDAO.addItem(buyer.getId(), item2.getId(), 4); // 101.00
        // Total should be 302.00
        Assert.assertEquals(new BigDecimal("302.00"), cartDAO.getCartTotal(buyer.getId()));

        // Clear cart
        boolean cleared = cartDAO.clearCart(buyer.getId());
        Assert.assertTrue(cleared);
        Assert.assertTrue(cartDAO.getCartItems(buyer.getId()).isEmpty());
        Assert.assertEquals(BigDecimal.ZERO, cartDAO.getCartTotal(buyer.getId()));
    }
}
