package com.rashik.rashikmart.dao;

import com.rashik.rashikmart.config.DatabaseConfig;
import com.rashik.rashikmart.model.Order;
import com.rashik.rashikmart.model.OrderItem;
import com.rashik.rashikmart.model.Product;
import com.rashik.rashikmart.model.SellerOrderItem;
import com.rashik.rashikmart.model.User;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;

public class OrderDAOTest {

    private static UserDAO userDAO;
    private static ProductDAO productDAO;
    private static CartDAO cartDAO;
    private static OrderDAO orderDAO;

    @BeforeClass
    public static void setUp() throws Exception {
        userDAO = new UserDAO();
        productDAO = new ProductDAO();
        cartDAO = new CartDAO();
        orderDAO = new OrderDAO();

        try (Connection conn = DatabaseConfig.getDataSource().getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS users (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        email VARCHAR(150) NOT NULL UNIQUE,
                        password VARCHAR(255) NOT NULL,
                        role VARCHAR(30) NOT NULL
                    );
                    CREATE TABLE IF NOT EXISTS products (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        seller_id INT NOT NULL,
                        name VARCHAR(150) NOT NULL,
                        description VARCHAR(1000),
                        category VARCHAR(100) NOT NULL,
                        price DECIMAL(12,2) NOT NULL,
                        quantity INT NOT NULL,
                        image_url VARCHAR(255) DEFAULT 'default-product.svg',
                        active BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS cart (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        buyer_id INT NOT NULL UNIQUE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_cart_buyer FOREIGN KEY (buyer_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS cart_items (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        cart_id INT NOT NULL,
                        product_id INT NOT NULL,
                        quantity INT NOT NULL,
                        CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
                        CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
                        CONSTRAINT uq_cart_product UNIQUE (cart_id, product_id)
                    );
                    CREATE TABLE IF NOT EXISTS orders (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        buyer_id INT NOT NULL,
                        total_amount DECIMAL(12,2) NOT NULL,
                        status VARCHAR(50) DEFAULT 'CONFIRMED',
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS order_items (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_id INT NOT NULL,
                        product_id INT NOT NULL,
                        quantity INT NOT NULL,
                        price DECIMAL(12,2) NOT NULL,
                        CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
                        CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id)
                    );
                    """);
        }
    }

    @Test
    public void testEmptyCartCheckoutFails() {
        String prefix = UUID.randomUUID().toString().substring(0, 8);
        userDAO.registerUser(new User("Empty Buyer", "empty_" + prefix + "@test.com", "pass", "BUYER"));
        User buyer = userDAO.findByEmail("empty_" + prefix + "@test.com");

        try {
            orderDAO.createOrderFromCart(buyer.getId());
            Assert.fail("Empty cart checkout should throw IllegalStateException");
        } catch (IllegalStateException e) {
            Assert.assertTrue(e.getMessage().contains("cart is empty"));
        } catch (Exception e) {
            Assert.fail("Unexpected exception: " + e.getMessage());
        }
    }

    @Test
    public void testTransactionalCheckoutStockDeductionAndCartClear() throws Exception {
        String prefix = UUID.randomUUID().toString().substring(0, 8);
        userDAO.registerUser(new User("S1", "s1_" + prefix + "@test.com", "pass", "SELLER"));
        userDAO.registerUser(new User("B1", "b1_" + prefix + "@test.com", "pass", "BUYER"));
        User seller = userDAO.findByEmail("s1_" + prefix + "@test.com");
        User buyer = userDAO.findByEmail("b1_" + prefix + "@test.com");

        Product product = new Product(seller.getId(), "Honey", "Pure honey", "Pantry", new BigDecimal("150.00"), 20);
        productDAO.addProduct(product);
        Product created = productDAO.findBySellerId(seller.getId()).get(0);

        cartDAO.addItem(buyer.getId(), created.getId(), 4);
        Order order = orderDAO.createOrderFromCart(buyer.getId());

        Assert.assertNotNull(order);
        Assert.assertEquals(new BigDecimal("600.00"), order.getTotalAmount());
        Assert.assertEquals(buyer.getId(), order.getBuyerId());

        // Stock deducted from 20 to 16
        Product refreshed = productDAO.findById(created.getId());
        Assert.assertEquals(16, refreshed.getQuantity());

        // Cart emptied
        Assert.assertTrue(cartDAO.getCartItems(buyer.getId()).isEmpty());

        // Buyer order lookup
        List<Order> buyerOrders = orderDAO.findOrdersByBuyerId(buyer.getId());
        Assert.assertEquals(1, buyerOrders.size());
        Assert.assertEquals(order.getId(), buyerOrders.get(0).getId());

        // Find by ID and buyer ID
        Order found = orderDAO.findOrderById(order.getId(), buyer.getId());
        Assert.assertNotNull(found);
        Assert.assertEquals(order.getId(), found.getId());

        // Order items
        List<OrderItem> items = orderDAO.findOrderItems(order.getId());
        Assert.assertEquals(1, items.size());
        Assert.assertEquals(4, items.get(0).getQuantity());
        Assert.assertEquals(new BigDecimal("150.00"), items.get(0).getPrice());
    }

    @Test
    public void testSellerOrdersIsolationAndRevenue() throws Exception {
        String prefix = UUID.randomUUID().toString().substring(0, 8);
        userDAO.registerUser(new User("Seller Alpha", "alpha_" + prefix + "@test.com", "pass", "SELLER"));
        userDAO.registerUser(new User("Seller Beta", "beta_" + prefix + "@test.com", "pass", "SELLER"));
        userDAO.registerUser(new User("Buyer Combo", "combo_" + prefix + "@test.com", "pass", "BUYER"));

        User sellerA = userDAO.findByEmail("alpha_" + prefix + "@test.com");
        User sellerB = userDAO.findByEmail("beta_" + prefix + "@test.com");
        User buyer = userDAO.findByEmail("combo_" + prefix + "@test.com");

        productDAO.addProduct(new Product(sellerA.getId(), "Alpha Bread", "desc", "Bakery", new BigDecimal("40.00"), 50));
        productDAO.addProduct(new Product(sellerB.getId(), "Beta Butter", "desc", "Dairy", new BigDecimal("70.00"), 50));

        Product prodA = productDAO.findBySellerId(sellerA.getId()).get(0);
        Product prodB = productDAO.findBySellerId(sellerB.getId()).get(0);

        cartDAO.addItem(buyer.getId(), prodA.getId(), 3); // 3 * 40 = 120.00
        cartDAO.addItem(buyer.getId(), prodB.getId(), 2); // 2 * 70 = 140.00
        Order order = orderDAO.createOrderFromCart(buyer.getId());
        Assert.assertNotNull(order);

        // Seller A should see ONLY product A
        List<SellerOrderItem> sellerAOrders = orderDAO.findSellerOrders(sellerA.getId());
        Assert.assertEquals(1, sellerAOrders.size());
        Assert.assertEquals(prodA.getId(), sellerAOrders.get(0).getProductId());
        Assert.assertEquals(new BigDecimal("120.00"), orderDAO.getSellerRevenue(sellerA.getId()));
        Assert.assertEquals(1, orderDAO.getSellerTotalOrders(sellerA.getId()));

        // Seller B should see ONLY product B
        List<SellerOrderItem> sellerBOrders = orderDAO.findSellerOrders(sellerB.getId());
        Assert.assertEquals(1, sellerBOrders.size());
        Assert.assertEquals(prodB.getId(), sellerBOrders.get(0).getProductId());
        Assert.assertEquals(new BigDecimal("140.00"), orderDAO.getSellerRevenue(sellerB.getId()));
        Assert.assertEquals(1, orderDAO.getSellerTotalOrders(sellerB.getId()));
    }

    @Test
    public void testBuyerOrderAuthorizationIsolation() throws Exception {
        String prefix = UUID.randomUUID().toString().substring(0, 8);
        userDAO.registerUser(new User("Seller Auth", "sauth_" + prefix + "@test.com", "pass", "SELLER"));
        userDAO.registerUser(new User("Buyer One", "bone_" + prefix + "@test.com", "pass", "BUYER"));
        userDAO.registerUser(new User("Buyer Two", "btwo_" + prefix + "@test.com", "pass", "BUYER"));

        User seller = userDAO.findByEmail("sauth_" + prefix + "@test.com");
        User buyer1 = userDAO.findByEmail("bone_" + prefix + "@test.com");
        User buyer2 = userDAO.findByEmail("btwo_" + prefix + "@test.com");

        productDAO.addProduct(new Product(seller.getId(), "Cookies", "desc", "Snacks", new BigDecimal("25.00"), 100));
        Product prod = productDAO.findBySellerId(seller.getId()).get(0);

        cartDAO.addItem(buyer1.getId(), prod.getId(), 2);
        Order order1 = orderDAO.createOrderFromCart(buyer1.getId());

        // Owner can access
        Assert.assertNotNull(orderDAO.findOrderById(order1.getId(), buyer1.getId()));

        // Other buyer cannot access order1
        Assert.assertNull("Non-owner buyer must be barred from accessing order",
                orderDAO.findOrderById(order1.getId(), buyer2.getId()));
    }

    @Test
    public void testFindAllOrdersAndPlatformMetrics() throws Exception {
        List<Order> allOrders = orderDAO.findAllOrders();
        Assert.assertNotNull(allOrders);

        BigDecimal revenue = orderDAO.getPlatformTotalRevenue();
        Assert.assertNotNull(revenue);

        int totalOrders = orderDAO.getPlatformTotalOrders();
        Assert.assertTrue(totalOrders >= 0);
    }
}
