package com.rashik.rashikmart.dao;

import com.rashik.rashikmart.config.DatabaseConfig;
import com.rashik.rashikmart.model.Order;
import com.rashik.rashikmart.model.Product;
import com.rashik.rashikmart.model.User;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;

public class ProductDAOTest {

    private static UserDAO userDAO;
    private static ProductDAO productDAO;
    private static CartDAO cartDAO;
    private static OrderDAO orderDAO;
    private static User seller;
    private static User buyer;

    @BeforeClass
    public static void setUp() throws Exception {
        userDAO = new UserDAO();
        productDAO = new ProductDAO();
        cartDAO = new CartDAO();
        orderDAO = new OrderDAO();

        try (Connection conn = DatabaseConfig.getDataSource().getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS users (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        email VARCHAR(150) NOT NULL UNIQUE,
                        password VARCHAR(255) NOT NULL,
                        role VARCHAR(30) NOT NULL
                    );
                    CREATE TABLE IF NOT EXISTS products (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        seller_id INT NOT NULL,
                        name VARCHAR(150) NOT NULL,
                        description VARCHAR(1000),
                        category VARCHAR(100) NOT NULL,
                        price DECIMAL(12,2) NOT NULL,
                        quantity INT NOT NULL,
                        image_url VARCHAR(255) DEFAULT 'default-product.svg',
                        active BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS cart (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        buyer_id INT NOT NULL UNIQUE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_cart_buyer FOREIGN KEY (buyer_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS cart_items (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        cart_id INT NOT NULL,
                        product_id INT NOT NULL,
                        quantity INT NOT NULL,
                        CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
                        CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
                        CONSTRAINT uq_cart_product UNIQUE (cart_id, product_id)
                    );
                    CREATE TABLE IF NOT EXISTS orders (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        buyer_id INT NOT NULL,
                        total_amount DECIMAL(12,2) NOT NULL,
                        status VARCHAR(50) DEFAULT 'CONFIRMED',
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS order_items (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_id INT NOT NULL,
                        product_id INT NOT NULL,
                        quantity INT NOT NULL,
                        price DECIMAL(12,2) NOT NULL,
                        CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
                        CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id)
                    );
                    """);
        }

        String prefix = UUID.randomUUID().toString().substring(0, 8);
        userDAO.registerUser(new User("Prod Seller", "pseller_" + prefix + "@test.com", "pass123", "SELLER"));
        userDAO.registerUser(new User("Prod Buyer", "pbuyer_" + prefix + "@test.com", "pass123", "BUYER"));
        seller = userDAO.findByEmail("pseller_" + prefix + "@test.com");
        buyer = userDAO.findByEmail("pbuyer_" + prefix + "@test.com");
    }

    @Test
    public void testAddAndFindProductById() {
        Product p = new Product(seller.getId(), "Fresh Mangoes", "Sweet Alphonso", "Fruits", new BigDecimal("250.00"), 30);
        boolean added = productDAO.addProduct(p);
        Assert.assertTrue(added);

        List<Product> sellerProducts = productDAO.findBySellerId(seller.getId());
        Assert.assertFalse(sellerProducts.isEmpty());
        Product found = sellerProducts.get(0);
        Assert.assertEquals("Fresh Mangoes", found.getName());
        Assert.assertEquals("Sweet Alphonso", found.getDescription());
        Assert.assertEquals("Fruits", found.getCategory());
        Assert.assertEquals(new BigDecimal("250.00"), found.getPrice());
        Assert.assertEquals(30, found.getQuantity());

        Product byId = productDAO.findById(found.getId());
        Assert.assertNotNull(byId);
        Assert.assertEquals(found.getId(), byId.getId());

        Product byIdAndSeller = productDAO.findByIdAndSellerId(found.getId(), seller.getId());
        Assert.assertNotNull(byIdAndSeller);
        Assert.assertEquals(found.getId(), byIdAndSeller.getId());

        // Mismatched seller should return null
        Product mismatchedSeller = productDAO.findByIdAndSellerId(found.getId(), seller.getId() + 999);
        Assert.assertNull(mismatchedSeller);
    }

    @Test
    public void testUpdateProduct() {
        Product p = new Product(seller.getId(), "Original Product", "Original Desc", "Dairy", new BigDecimal("45.00"), 15);
        productDAO.addProduct(p);
        List<Product> products = productDAO.findBySellerId(seller.getId());
        Product created = null;
        for (Product item : products) {
            if ("Original Product".equals(item.getName())) {
                created = item;
                break;
            }
        }
        Assert.assertNotNull(created);

        created.setName("Updated Product Name");
        created.setDescription("Updated Desc");
        created.setCategory("Dairy & Eggs");
        created.setPrice(new BigDecimal("55.00"));
        created.setQuantity(25);
        created.setImageUrl("updated.png");

        boolean updated = productDAO.updateProduct(created);
        Assert.assertTrue("Product update should succeed", updated);

        Product refreshed = productDAO.findById(created.getId());
        Assert.assertEquals("Updated Product Name", refreshed.getName());
        Assert.assertEquals("Updated Desc", refreshed.getDescription());
        Assert.assertEquals("Dairy & Eggs", refreshed.getCategory());
        Assert.assertEquals(new BigDecimal("55.00"), refreshed.getPrice());
        Assert.assertEquals(25, refreshed.getQuantity());
        Assert.assertEquals("updated.png", refreshed.getImageUrl());
    }

    @Test
    public void testUpdateStockDirectly() {
        Product p = new Product(seller.getId(), "Stock Item", "desc", "Snacks", new BigDecimal("10.00"), 100);
        productDAO.addProduct(p);
        List<Product> products = productDAO.findBySellerId(seller.getId());
        Product created = null;
        for (Product item : products) {
            if ("Stock Item".equals(item.getName())) {
                created = item;
                break;
            }
        }
        Assert.assertNotNull(created);

        boolean stockUpdated = productDAO.updateStock(created.getId(), 77);
        Assert.assertTrue(stockUpdated);

        Product refreshed = productDAO.findById(created.getId());
        Assert.assertEquals(77, refreshed.getQuantity());
    }

    @Test
    public void testFindAllAvailableExcludesZeroStockAndInactive() {
        // Zero stock product
        Product zeroStock = new Product(seller.getId(), "Zero Stock Item", "desc", "Pantry", new BigDecimal("20.00"), 0);
        productDAO.addProduct(zeroStock);

        // Inactive product
        Product inactive = new Product(seller.getId(), "Inactive Item", "desc", "Pantry", new BigDecimal("30.00"), 50);
        productDAO.addProduct(inactive);
        List<Product> sellerList = productDAO.findBySellerId(seller.getId());
        Product createdInactive = null;
        for (Product item : sellerList) {
            if ("Inactive Item".equals(item.getName())) {
                createdInactive = item;
                break;
            }
        }
        Assert.assertNotNull(createdInactive);
        productDAO.toggleProductActive(createdInactive.getId(), false);

        List<Product> available = productDAO.findAllAvailable();
        for (Product p : available) {
            Assert.assertNotEquals("Zero Stock Item", p.getName());
            Assert.assertNotEquals("Inactive Item", p.getName());
            Assert.assertTrue(p.getQuantity() > 0);
            Assert.assertTrue(p.isActive());
        }
    }

    @Test
    public void testDeleteProductBranching() throws Exception {
        // 1. Physical delete when no orders exist
        Product unpurchased = new Product(seller.getId(), "ToDelete", "desc", "Household", new BigDecimal("10.00"), 5);
        productDAO.addProduct(unpurchased);
        List<Product> list = productDAO.findBySellerId(seller.getId());
        Product createdUnpurchased = null;
        for (Product item : list) {
            if ("ToDelete".equals(item.getName())) {
                createdUnpurchased = item;
                break;
            }
        }
        Assert.assertNotNull(createdUnpurchased);

        ProductDAO.DeletionResult delRes = productDAO.deleteProduct(createdUnpurchased.getId(), seller.getId());
        Assert.assertEquals(ProductDAO.DeletionResult.DELETED, delRes);
        Assert.assertNull(productDAO.findById(createdUnpurchased.getId()));

        // 2. Safe deactivation when order exists
        Product purchased = new Product(seller.getId(), "ToDeactivate", "desc", "Household", new BigDecimal("15.00"), 10);
        productDAO.addProduct(purchased);
        list = productDAO.findBySellerId(seller.getId());
        Product createdPurchased = null;
        for (Product item : list) {
            if ("ToDeactivate".equals(item.getName())) {
                createdPurchased = item;
                break;
            }
        }
        Assert.assertNotNull(createdPurchased);

        // Buyer purchases 1 unit
        cartDAO.addItem(buyer.getId(), createdPurchased.getId(), 1);
        Order order = orderDAO.createOrderFromCart(buyer.getId());
        Assert.assertNotNull(order);

        ProductDAO.DeletionResult deactRes = productDAO.deleteProduct(createdPurchased.getId(), seller.getId());
        Assert.assertEquals(ProductDAO.DeletionResult.DEACTIVATED, deactRes);

        Product stillExists = productDAO.findById(createdPurchased.getId());
        Assert.assertNotNull(stillExists);
        Assert.assertFalse("Product should now be inactive", stillExists.isActive());

        // 3. Not found when wrong seller tries to delete
        ProductDAO.DeletionResult wrongSellerRes = productDAO.deleteProduct(createdPurchased.getId(), seller.getId() + 9999);
        Assert.assertEquals(ProductDAO.DeletionResult.NOT_FOUND, wrongSellerRes);
    }
}
