package com.rashik.rashikmart.dao;

import com.rashik.rashikmart.config.DatabaseConfig;
import com.rashik.rashikmart.model.Product;
import com.rashik.rashikmart.model.Review;
import com.rashik.rashikmart.model.User;
import com.rashik.rashikmart.util.HtmlUtil;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;

public class ReviewDAOTest {

    private static UserDAO userDAO;
    private static ProductDAO productDAO;
    private static CartDAO cartDAO;
    private static OrderDAO orderDAO;
    private static ReviewDAO reviewDAO;

    @BeforeClass
    public static void setUp() throws Exception {
        userDAO = new UserDAO();
        productDAO = new ProductDAO();
        cartDAO = new CartDAO();
        orderDAO = new OrderDAO();
        reviewDAO = new ReviewDAO();

        try (Connection conn = DatabaseConfig.getDataSource().getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS users (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        email VARCHAR(150) NOT NULL UNIQUE,
                        password VARCHAR(255) NOT NULL,
                        role VARCHAR(30) NOT NULL
                    );
                    CREATE TABLE IF NOT EXISTS products (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        seller_id INT NOT NULL,
                        name VARCHAR(150) NOT NULL,
                        description VARCHAR(1000),
                        category VARCHAR(100) NOT NULL,
                        price DECIMAL(12,2) NOT NULL,
                        quantity INT NOT NULL,
                        image_url VARCHAR(255) DEFAULT 'default-product.svg',
                        active BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS cart (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        buyer_id INT NOT NULL UNIQUE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_cart_buyer FOREIGN KEY (buyer_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS cart_items (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        cart_id INT NOT NULL,
                        product_id INT NOT NULL,
                        quantity INT NOT NULL,
                        CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
                        CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
                        CONSTRAINT uq_cart_product UNIQUE (cart_id, product_id)
                    );
                    CREATE TABLE IF NOT EXISTS orders (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        buyer_id INT NOT NULL,
                        total_amount DECIMAL(12,2) NOT NULL,
                        status VARCHAR(50) DEFAULT 'CONFIRMED',
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS order_items (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_id INT NOT NULL,
                        product_id INT NOT NULL,
                        quantity INT NOT NULL,
                        price DECIMAL(12,2) NOT NULL,
                        CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
                        CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id)
                    );
                    CREATE TABLE IF NOT EXISTS reviews (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        product_id INT NOT NULL,
                        buyer_id INT NOT NULL,
                        rating INT NOT NULL,
                        review_text VARCHAR(500),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
                        CONSTRAINT fk_reviews_buyer FOREIGN KEY (buyer_id) REFERENCES users(id),
                        CONSTRAINT uq_reviews_product_buyer UNIQUE (product_id, buyer_id)
                    );
                    """);
        }
    }

    // =========================================================
    // Fixtures
    // =========================================================

    private static class PurchasedFixture {
        final User seller;
        final User buyer;
        final Product product;

        PurchasedFixture(User seller, User buyer, Product product) {
            this.seller = seller;
            this.buyer = buyer;
            this.product = product;
        }
    }

    private static User newUser(String name, String role) throws Exception {
        String prefix = UUID.randomUUID().toString().substring(0, 8);
        String email = prefix + "_" + UUID.randomUUID().toString().substring(0, 8) + "@test.com";
        userDAO.registerUser(new User(name, email, "pass", role));
        User created = userDAO.findByEmail(email);
        Assert.assertNotNull(created);
        return created;
    }

    private static PurchasedFixture purchaseSingleProduct() throws Exception {
        User seller = newUser("Seller " + UUID.randomUUID().toString().substring(0, 4), "SELLER");
        User buyer = newUser("Buyer " + UUID.randomUUID().toString().substring(0, 4), "BUYER");

        productDAO.addProduct(new Product(
                seller.getId(),
                "Reviewable Product",
                "desc",
                "General",
                new BigDecimal("100.00"),
                50
        ));
        Product product = productDAO.findBySellerId(seller.getId()).get(0);

        cartDAO.addItem(buyer.getId(), product.getId(), 2);
        orderDAO.createOrderFromCart(buyer.getId());

        return new PurchasedFixture(seller, buyer, product);
    }

    // =========================================================
    // Tests
    // =========================================================

    @Test
    public void testPurchasedBuyerCanSubmitValidReview() throws Exception {
        PurchasedFixture fixture = purchaseSingleProduct();

        Review created = reviewDAO.addReview(
                fixture.buyer.getId(),
                fixture.product.getId(),
                5,
                "Excellent quality, highly recommended!"
        );

        Assert.assertNotNull(created);
        Assert.assertTrue(created.getId() > 0);
        Assert.assertEquals(5, created.getRating());
        Assert.assertEquals("Excellent quality, highly recommended!", created.getReviewText());
        Assert.assertEquals(fixture.product.getId(), created.getProductId());

        Assert.assertTrue(reviewDAO.hasReviewByBuyer(fixture.buyer.getId(), fixture.product.getId()));
        Assert.assertEquals(1, reviewDAO.getReviewCount(fixture.product.getId()));
        Assert.assertEquals(5.0, reviewDAO.getAverageRating(fixture.product.getId()), 0.0001);

        List<Review> reviews = reviewDAO.findByProductId(fixture.product.getId());
        Assert.assertEquals(1, reviews.size());
        Assert.assertEquals(fixture.buyer.getName(), reviews.get(0).getBuyerName());
        Assert.assertEquals(5, reviews.get(0).getRating());
    }

    @Test
    public void testInvalidRatingRejected() throws Exception {
        PurchasedFixture fixture = purchaseSingleProduct();

        try {
            reviewDAO.addReview(fixture.buyer.getId(), fixture.product.getId(), 0, "bad");
            Assert.fail("Rating 0 should be rejected");
        } catch (IllegalArgumentException e) {
            Assert.assertEquals("Rating must be between 1 and 5.", e.getMessage());
        }

        try {
            reviewDAO.addReview(fixture.buyer.getId(), fixture.product.getId(), 6, "bad");
            Assert.fail("Rating 6 should be rejected");
        } catch (IllegalArgumentException e) {
            Assert.assertEquals("Rating must be between 1 and 5.", e.getMessage());
        }

        Assert.assertEquals(0, reviewDAO.getReviewCount(fixture.product.getId()));
    }

    @Test
    public void testBuyerWhoDidNotPurchaseRejected() throws Exception {
        User seller = newUser("Seller Only " + UUID.randomUUID().toString().substring(0, 4), "SELLER");
        User nonBuyer = newUser("Non Purchaser " + UUID.randomUUID().toString().substring(0, 4), "BUYER");

        productDAO.addProduct(new Product(
                seller.getId(),
                "Unpurchased Product",
                "desc",
                "General",
                new BigDecimal("50.00"),
                10
        ));
        Product product = productDAO.findBySellerId(seller.getId()).get(0);

        Assert.assertFalse(reviewDAO.hasPurchasedProduct(nonBuyer.getId(), product.getId()));

        try {
            reviewDAO.addReview(nonBuyer.getId(), product.getId(), 4, "fake");
            Assert.fail("Review without purchase should be rejected");
        } catch (IllegalStateException e) {
            Assert.assertEquals("You must purchase this product before reviewing it.", e.getMessage());
        }

        Assert.assertEquals(0, reviewDAO.getReviewCount(product.getId()));
    }

    @Test
    public void testDuplicateReviewPrevention() throws Exception {
        PurchasedFixture fixture = purchaseSingleProduct();

        reviewDAO.addReview(fixture.buyer.getId(), fixture.product.getId(), 4, "First review");

        try {
            reviewDAO.addReview(fixture.buyer.getId(), fixture.product.getId(), 1, "Second attempt");
            Assert.fail("Duplicate review should be rejected");
        } catch (IllegalStateException e) {
            Assert.assertEquals("You have already reviewed this product.", e.getMessage());
        }

        Assert.assertEquals(1, reviewDAO.getReviewCount(fixture.product.getId()));
        List<Review> reviews = reviewDAO.findByProductId(fixture.product.getId());
        Assert.assertEquals(1, reviews.size());
        Assert.assertEquals(4, reviews.get(0).getRating());
        Assert.assertEquals("First review", reviews.get(0).getReviewText());
    }

    @Test
    public void testXssPayloadHandledSafely() throws Exception {
        PurchasedFixture fixture = purchaseSingleProduct();

        String xssPayload = "<script>alert('XSS')</script><img src=x onerror=alert(1)>";

        reviewDAO.addReview(fixture.buyer.getId(), fixture.product.getId(), 3, xssPayload);

        List<Review> reviews = reviewDAO.findByProductId(fixture.product.getId());
        Assert.assertEquals(1, reviews.size());
        Assert.assertEquals(xssPayload, reviews.get(0).getReviewText());

        String escaped = HtmlUtil.escape(reviews.get(0).getReviewText());
        Assert.assertFalse(escaped.contains("<script>"));
        Assert.assertFalse(escaped.contains("<img"));
        Assert.assertTrue(escaped.contains("&lt;script&gt;"));
    }

    @Test
    public void testSqlInjectionPayloadHandledSafely() throws Exception {
        PurchasedFixture fixture = purchaseSingleProduct();

        String sqlPayload = "' OR '1'='1 --";

        reviewDAO.addReview(fixture.buyer.getId(), fixture.product.getId(), 4, sqlPayload);

        List<Review> reviews = reviewDAO.findByProductId(fixture.product.getId());
        Assert.assertEquals(1, reviews.size());
        Assert.assertEquals(sqlPayload, reviews.get(0).getReviewText());

        Assert.assertEquals(1, reviewDAO.getReviewCount(fixture.product.getId()));
        Assert.assertEquals(4.0, reviewDAO.getAverageRating(fixture.product.getId()), 0.0001);
        Assert.assertNotNull(reviewDAO.findByProductId(fixture.product.getId()));

        Product product = productDAO.findById(fixture.product.getId());
        Assert.assertNotNull(product);
        Assert.assertEquals(48, product.getQuantity());
    }

    @Test
    public void testAverageRatingAndReviewCountCalculatedCorrectly() throws Exception {
        User seller = newUser("Multi Seller " + UUID.randomUUID().toString().substring(0, 4), "SELLER");
        User buyer1 = newUser("Multi Buyer 1 " + UUID.randomUUID().toString().substring(0, 4), "BUYER");
        User buyer2 = newUser("Multi Buyer 2 " + UUID.randomUUID().toString().substring(0, 4), "BUYER");

        productDAO.addProduct(new Product(
                seller.getId(),
                "Multi Review Product",
                "desc",
                "General",
                new BigDecimal("30.00"),
                100
        ));
        Product product = productDAO.findBySellerId(seller.getId()).get(0);

        cartDAO.addItem(buyer1.getId(), product.getId(), 1);
        orderDAO.createOrderFromCart(buyer1.getId());

        cartDAO.addItem(buyer2.getId(), product.getId(), 1);
        orderDAO.createOrderFromCart(buyer2.getId());

        reviewDAO.addReview(buyer1.getId(), product.getId(), 4, "Very good");
        reviewDAO.addReview(buyer2.getId(), product.getId(), 2, "Could be better");

        Assert.assertEquals(2, reviewDAO.getReviewCount(product.getId()));
        Assert.assertEquals(3.0, reviewDAO.getAverageRating(product.getId()), 0.0001);

        List<Review> reviews = reviewDAO.findByProductId(product.getId());
        Assert.assertEquals(2, reviews.size());

        Review newest = reviews.get(0);
        Assert.assertEquals(buyer2.getId(), newest.getBuyerId());
        Assert.assertEquals(2, newest.getRating());
    }
}