package com.rashik.rashikmart.dao;

import com.rashik.rashikmart.config.DatabaseConfig;
import com.rashik.rashikmart.model.User;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;

public class UserDAOTest {

    private static UserDAO userDAO;

    @BeforeClass
    public static void setUp() throws Exception {
        userDAO = new UserDAO();
        try (Connection conn = DatabaseConfig.getDataSource().getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS users (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        email VARCHAR(150) NOT NULL UNIQUE,
                        password VARCHAR(255) NOT NULL,
                        role VARCHAR(30) NOT NULL
                    );
                    """);
        }
    }

    @Test
    public void testRegisterUserSuccess() {
        String email = "reg_" + UUID.randomUUID().toString().substring(0, 8) + "@test.com";
        User user = new User("Alice Tester", email, "password123", "BUYER");
        boolean created = userDAO.registerUser(user);
        Assert.assertTrue("Registration should succeed", created);

        User found = userDAO.findByEmail(email);
        Assert.assertNotNull("User should be found by email", found);
        Assert.assertEquals("Alice Tester", found.getName());
        Assert.assertEquals(email, found.getEmail());
        Assert.assertEquals("BUYER", found.getRole());
        Assert.assertTrue("Password should be BCrypt hashed",
                found.getPassword().startsWith("$2a$") || found.getPassword().startsWith("$2b$"));
    }

    @Test
    public void testRegisterDuplicateEmailFails() {
        String email = "dup_" + UUID.randomUUID().toString().substring(0, 8) + "@test.com";
        User user1 = new User("First User", email, "pass1", "SELLER");
        boolean first = userDAO.registerUser(user1);
        Assert.assertTrue(first);

        User user2 = new User("Second User", email, "pass2", "BUYER");
        boolean second = userDAO.registerUser(user2);
        Assert.assertFalse("Duplicate email registration must fail due to unique constraint", second);
    }

    @Test
    public void testFindById() {
        String email = "findbyid_" + UUID.randomUUID().toString().substring(0, 8) + "@test.com";
        User user = new User("Bob ById", email, "secret", "BUYER");
        userDAO.registerUser(user);

        User byEmail = userDAO.findByEmail(email);
        Assert.assertNotNull(byEmail);
        Assert.assertTrue(byEmail.getId() > 0);

        User byId = userDAO.findById(byEmail.getId());
        Assert.assertNotNull("User should be found by ID", byId);
        Assert.assertEquals(byEmail.getId(), byId.getId());
        Assert.assertEquals("Bob ById", byId.getName());
        Assert.assertEquals(email, byId.getEmail());
    }

    @Test
    public void testFindByNonExistentEmailAndIdReturnsNull() {
        User notFoundEmail = userDAO.findByEmail("non_existent_99999@domain.org");
        Assert.assertNull("Non-existent email should return null", notFoundEmail);

        User notFoundId = userDAO.findById(-9999);
        Assert.assertNull("Negative ID should return null", notFoundId);
    }

    @Test
    public void testVerifyPasswordLogic() {
        String email = "verify_" + UUID.randomUUID().toString().substring(0, 8) + "@test.com";
        String rawPassword = "StrongPassword$2026";
        User user = new User("Carol Verifier", email, rawPassword, "SELLER");
        userDAO.registerUser(user);

        User stored = userDAO.findByEmail(email);
        Assert.assertNotNull(stored);

        // Positive check
        Assert.assertTrue("Valid password should verify",
                userDAO.verifyPassword(rawPassword, stored.getPassword()));

        // Negative check
        Assert.assertFalse("Wrong password should fail verification",
                userDAO.verifyPassword("WrongPass", stored.getPassword()));

        // Null checks
        Assert.assertFalse("Null entered password should return false",
                userDAO.verifyPassword(null, stored.getPassword()));
        Assert.assertFalse("Null stored password should return false",
                userDAO.verifyPassword(rawPassword, null));
    }

    @Test
    public void testFindAllUsers() {
        List<User> initialUsers = userDAO.findAll();
        int initialCount = initialUsers.size();

        String email = "findall_" + UUID.randomUUID().toString().substring(0, 8) + "@test.com";
        userDAO.registerUser(new User("FindAll User", email, "pass", "BUYER"));

        List<User> updatedUsers = userDAO.findAll();
        Assert.assertEquals(initialCount + 1, updatedUsers.size());
    }
}
