package com.rashik.rashikmart;

import com.rashik.rashikmart.config.DatabaseConfig;
import com.rashik.rashikmart.dao.CartDAO;
import com.rashik.rashikmart.dao.OrderDAO;
import com.rashik.rashikmart.dao.ProductDAO;
import com.rashik.rashikmart.dao.UserDAO;
import com.rashik.rashikmart.model.Order;
import com.rashik.rashikmart.model.OrderItem;
import com.rashik.rashikmart.model.Product;
import com.rashik.rashikmart.model.SellerOrderItem;
import com.rashik.rashikmart.model.User;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RashikMartFlowTest {

    private static UserDAO userDAO;
    private static ProductDAO productDAO;
    private static CartDAO cartDAO;
    private static OrderDAO orderDAO;

    @BeforeClass
    public static void setUp() throws Exception {
        userDAO = new UserDAO();
        productDAO = new ProductDAO();
        cartDAO = new CartDAO();
        orderDAO = new OrderDAO();

        // Ensure tables exist
        try (Connection conn = DatabaseConfig.getDataSource().getConnection();
             Statement stmt = conn.createStatement()) {

            stmt.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS users (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        email VARCHAR(150) NOT NULL UNIQUE,
                        password VARCHAR(255) NOT NULL,
                        role VARCHAR(30) NOT NULL
                    );
                    CREATE TABLE IF NOT EXISTS products (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        seller_id INT NOT NULL,
                        name VARCHAR(150) NOT NULL,
                        description VARCHAR(1000),
                        category VARCHAR(100) NOT NULL,
                        price DECIMAL(12,2) NOT NULL,
                        quantity INT NOT NULL,
                        image_url VARCHAR(255) DEFAULT 'default-product.svg',
                        active BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS cart (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        buyer_id INT NOT NULL UNIQUE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_cart_buyer FOREIGN KEY (buyer_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS cart_items (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        cart_id INT NOT NULL,
                        product_id INT NOT NULL,
                        quantity INT NOT NULL,
                        CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
                        CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
                        CONSTRAINT uq_cart_product UNIQUE (cart_id, product_id)
                    );
                    CREATE TABLE IF NOT EXISTS orders (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        buyer_id INT NOT NULL,
                        total_amount DECIMAL(12,2) NOT NULL,
                        status VARCHAR(50) DEFAULT 'CONFIRMED',
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES users(id)
                    );
                    CREATE TABLE IF NOT EXISTS order_items (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_id INT NOT NULL,
                        product_id INT NOT NULL,
                        quantity INT NOT NULL,
                        price DECIMAL(12,2) NOT NULL,
                        CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
                        CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id)
                    );
                    """);
        }
    }

    @Test
    public void test01_UserRegistrationWithBCrypt() {
        String randomSuffix = UUID.randomUUID().toString().substring(0, 8);
        String email = "testbuyer_" + randomSuffix + "@test.com";
        String plainPassword = "SecretPassword123";

        User user = new User("Test Buyer", email, plainPassword, "BUYER");
        boolean registered = userDAO.registerUser(user);
        Assert.assertTrue("User registration should succeed", registered);

        User loaded = userDAO.findByEmail(email);
        Assert.assertNotNull("Loaded user should not be null", loaded);
        Assert.assertNotEquals("Password should be hashed with BCrypt, not plain text", plainPassword, loaded.getPassword());
        Assert.assertTrue("Password hash should start with $2a$", loaded.getPassword().startsWith("$2a$") || loaded.getPassword().startsWith("$2b$"));

        boolean verified = userDAO.verifyPassword(plainPassword, loaded.getPassword());
        Assert.assertTrue("Correct password should verify against BCrypt hash", verified);

        boolean wrongVerified = userDAO.verifyPassword("WrongPassword", loaded.getPassword());
        Assert.assertFalse("Incorrect password should fail verification", wrongVerified);
    }

    @Test
    public void test02_TransactionalCheckoutAndStockDeduction() throws Exception {
        String randomSuffix = UUID.randomUUID().toString().substring(0, 8);
        String sellerEmail = "seller_" + randomSuffix + "@test.com";
        String buyerEmail = "buyer_" + randomSuffix + "@test.com";

        userDAO.registerUser(new User("Test Seller", sellerEmail, "seller123", "SELLER"));
        userDAO.registerUser(new User("Test Buyer", buyerEmail, "buyer123", "BUYER"));

        User seller = userDAO.findByEmail(sellerEmail);
        User buyer = userDAO.findByEmail(buyerEmail);

        // Add Product
        Product product = new Product(
                seller.getId(),
                "Organic Basmati Rice",
                "Finest quality grain",
                "Grains",
                new BigDecimal("120.00"),
                50,
                "rice.jpg"
        );
        boolean added = productDAO.addProduct(product);
        Assert.assertTrue("Product addition should succeed", added);

        List<Product> sellerProducts = productDAO.findBySellerId(seller.getId());
        Assert.assertFalse("Seller should have listed products", sellerProducts.isEmpty());
        Product createdProduct = sellerProducts.get(0);
        int initialStock = createdProduct.getQuantity();

        // Buyer adds 5 units to cart
        boolean cartAdded = cartDAO.addItem(buyer.getId(), createdProduct.getId(), 5);
        Assert.assertTrue("Add to cart should succeed", cartAdded);

        BigDecimal cartTotal = cartDAO.getCartTotal(buyer.getId());
        Assert.assertEquals("Cart total should be 5 * 120.00 = 600.00", new BigDecimal("600.00"), cartTotal);

        // Buyer checks out
        Order order = orderDAO.createOrderFromCart(buyer.getId());
        Assert.assertNotNull("Order should be created", order);
        Assert.assertEquals("Order total should equal cart total", new BigDecimal("600.00"), order.getTotalAmount());
        Assert.assertEquals("Order status should be CONFIRMED", "CONFIRMED", order.getStatus());

        // Stock should be deducted: 50 - 5 = 45
        Product updatedProduct = productDAO.findById(createdProduct.getId());
        Assert.assertEquals("Stock should be deducted from 50 to 45", initialStock - 5, updatedProduct.getQuantity());

        // Cart should be empty after checkout
        Assert.assertTrue("Cart should be cleared after checkout", cartDAO.getCartItems(buyer.getId()).isEmpty());
    }

    @Test
    public void test03_SafeProductDeletionWithOrderHistory() {
        String randomSuffix = UUID.randomUUID().toString().substring(0, 8);
        String sellerEmail = "seller_del_" + randomSuffix + "@test.com";
        String buyerEmail = "buyer_del_" + randomSuffix + "@test.com";

        userDAO.registerUser(new User("Seller Del", sellerEmail, "seller123", "SELLER"));
        userDAO.registerUser(new User("Buyer Del", buyerEmail, "buyer123", "BUYER"));

        User seller = userDAO.findByEmail(sellerEmail);
        User buyer = userDAO.findByEmail(buyerEmail);

        // 1. Test Physical Delete for product with NO order history
        Product unpurchased = new Product(
                seller.getId(),
                "Unpurchased Tea",
                "Fresh leaves",
                "Beverages",
                new BigDecimal("50.00"),
                10,
                "tea.jpg"
        );
        productDAO.addProduct(unpurchased);
        Product loadedUnpurchased = productDAO.findBySellerId(seller.getId()).get(0);

        ProductDAO.DeletionResult delResult = productDAO.deleteProduct(loadedUnpurchased.getId(), seller.getId());
        Assert.assertEquals("Unpurchased product should be physically DELETED", ProductDAO.DeletionResult.DELETED, delResult);
        Assert.assertNull("Deleted product should not exist in database", productDAO.findById(loadedUnpurchased.getId()));

        // 2. Test Safe Deactivation for product WITH order history
        Product orderedProd = new Product(
                seller.getId(),
                "Purchased Cardamom",
                "Spices",
                "Spices",
                new BigDecimal("200.00"),
                20,
                "cardamom.jpg"
        );
        productDAO.addProduct(orderedProd);
        Product loadedOrderedProd = productDAO.findBySellerId(seller.getId()).get(0);

        cartDAO.addItem(buyer.getId(), loadedOrderedProd.getId(), 2);
        Order order = null;
        try {
            order = orderDAO.createOrderFromCart(buyer.getId());
        } catch (Exception e) {
            Assert.fail("Order creation failed: " + e.getMessage());
        }
        Assert.assertNotNull(order);

        // Delete requested for ordered product
        ProductDAO.DeletionResult deactResult = productDAO.deleteProduct(loadedOrderedProd.getId(), seller.getId());
        Assert.assertEquals("Ordered product must be safely DEACTIVATED, not physically deleted", ProductDAO.DeletionResult.DEACTIVATED, deactResult);

        // Must disappear from marketplace
        List<Product> marketplace = productDAO.findAllAvailable();
        for (Product p : marketplace) {
            Assert.assertNotEquals("Deactivated product must not appear in active marketplace", loadedOrderedProd.getId(), p.getId());
        }

        // Must NOT appear in seller active inventory
        List<Product> sellerCatalog = productDAO.findBySellerId(seller.getId());
        for (Product p : sellerCatalog) {
            Assert.assertNotEquals("Deactivated product must not appear in seller active inventory", loadedOrderedProd.getId(), p.getId());
        }

        // Must still be preserved in buyer's historical order items!
        List<OrderItem> historicalItems = orderDAO.findOrderItems(order.getId());
        Assert.assertFalse("Historical order items must remain intact", historicalItems.isEmpty());
        Assert.assertEquals("Historical item should match product ID", loadedOrderedProd.getId(), historicalItems.get(0).getProductId());
        Assert.assertNotNull("Historical product info should still be accessible", historicalItems.get(0).getProduct());
        Assert.assertEquals("Purchased Cardamom", historicalItems.get(0).getProduct().getName());
    }

    @Test
    public void test04_SellerOrderIsolation() throws Exception {
        String randomSuffix = UUID.randomUUID().toString().substring(0, 8);
        String sellerAEmail = "sellerA_" + randomSuffix + "@test.com";
        String sellerBEmail = "sellerB_" + randomSuffix + "@test.com";
        String buyerEmail = "buyer_iso_" + randomSuffix + "@test.com";

        userDAO.registerUser(new User("Seller A", sellerAEmail, "pass123", "SELLER"));
        userDAO.registerUser(new User("Seller B", sellerBEmail, "pass123", "SELLER"));
        userDAO.registerUser(new User("Buyer Multi", buyerEmail, "pass123", "BUYER"));

        User sellerA = userDAO.findByEmail(sellerAEmail);
        User sellerB = userDAO.findByEmail(sellerBEmail);
        User buyer = userDAO.findByEmail(buyerEmail);

        // Seller A creates Product A
        Product prodA = new Product(sellerA.getId(), "Apples from A", "Fresh", "Fruits", new BigDecimal("150.00"), 30);
        productDAO.addProduct(prodA);
        Product createdProdA = productDAO.findBySellerId(sellerA.getId()).get(0);

        // Seller B creates Product B
        Product prodB = new Product(sellerB.getId(), "Bananas from B", "Sweet", "Fruits", new BigDecimal("60.00"), 40);
        productDAO.addProduct(prodB);
        Product createdProdB = productDAO.findBySellerId(sellerB.getId()).get(0);

        // Buyer adds both products to cart
        cartDAO.addItem(buyer.getId(), createdProdA.getId(), 2); // 2 * 150 = 300
        cartDAO.addItem(buyer.getId(), createdProdB.getId(), 3); // 3 * 60 = 180

        Order order = orderDAO.createOrderFromCart(buyer.getId());
        Assert.assertNotNull(order);

        // Seller A views customer orders
        List<SellerOrderItem> sellerAOrders = orderDAO.findSellerOrders(sellerA.getId());
        Assert.assertFalse("Seller A should have orders", sellerAOrders.isEmpty());
        for (SellerOrderItem item : sellerAOrders) {
            Assert.assertEquals("Seller A should ONLY see Seller A's product", createdProdA.getId(), item.getProductId());
            Assert.assertNotEquals("Seller A must NEVER see Seller B's product", createdProdB.getId(), item.getProductId());
        }
        Assert.assertEquals("Seller A revenue should be exactly 300.00", new BigDecimal("300.00"), orderDAO.getSellerRevenue(sellerA.getId()));

        // Seller B views customer orders
        List<SellerOrderItem> sellerBOrders = orderDAO.findSellerOrders(sellerB.getId());
        Assert.assertFalse("Seller B should have orders", sellerBOrders.isEmpty());
        for (SellerOrderItem item : sellerBOrders) {
            Assert.assertEquals("Seller B should ONLY see Seller B's product", createdProdB.getId(), item.getProductId());
            Assert.assertNotEquals("Seller B must NEVER see Seller A's product", createdProdA.getId(), item.getProductId());
        }
        Assert.assertEquals("Seller B revenue should be exactly 180.00", new BigDecimal("180.00"), orderDAO.getSellerRevenue(sellerB.getId()));
    }

    @Test
    public void test05_BuyerOrderAccessControl() throws Exception {
        String randomSuffix = UUID.randomUUID().toString().substring(0, 8);
        String sellerEmail = "seller_ac_" + randomSuffix + "@test.com";
        String buyer1Email = "buyer1_" + randomSuffix + "@test.com";
        String buyer2Email = "buyer2_" + randomSuffix + "@test.com";

        userDAO.registerUser(new User("Seller AC", sellerEmail, "pass123", "SELLER"));
        userDAO.registerUser(new User("Buyer One", buyer1Email, "pass123", "BUYER"));
        userDAO.registerUser(new User("Buyer Two", buyer2Email, "pass123", "BUYER"));

        User seller = userDAO.findByEmail(sellerEmail);
        User buyer1 = userDAO.findByEmail(buyer1Email);
        User buyer2 = userDAO.findByEmail(buyer2Email);

        Product prod = new Product(seller.getId(), "Pears", "Juicy", "Fruits", new BigDecimal("90.00"), 25);
        productDAO.addProduct(prod);
        Product createdProd = productDAO.findBySellerId(seller.getId()).get(0);

        // Buyer 1 places order
        cartDAO.addItem(buyer1.getId(), createdProd.getId(), 1);
        Order order1 = orderDAO.createOrderFromCart(buyer1.getId());
        Assert.assertNotNull(order1);

        // Buyer 1 can find their own order
        Order foundByOwner = orderDAO.findOrderById(order1.getId(), buyer1.getId());
        Assert.assertNotNull("Buyer 1 should access their own order", foundByOwner);

        // Buyer 2 attempting to access Buyer 1's order MUST BE REJECTED
        Order foundByOther = orderDAO.findOrderById(order1.getId(), buyer2.getId());
        Assert.assertNull("Buyer 2 MUST NOT be able to access Buyer 1's order", foundByOther);
    }

    @Test
    public void test06_AdminPlatformOversightAndProductToggle() {
        String randomSuffix = UUID.randomUUID().toString().substring(0, 8);
        String sellerEmail = "seller_adm_" + randomSuffix + "@test.com";
        userDAO.registerUser(new User("Seller Adm", sellerEmail, "pass123", "SELLER"));
        User seller = userDAO.findByEmail(sellerEmail);

        Product prod = new Product(seller.getId(), "Admin Oversight Item", "Testing", "Other", new BigDecimal("75.00"), 10);
        productDAO.addProduct(prod);
        Product createdProd = productDAO.findBySellerId(seller.getId()).get(0);

        // Admin toggles active to false
        boolean toggledOff = productDAO.toggleProductActive(createdProd.getId(), false);
        Assert.assertTrue(toggledOff);
        Product deactivated = productDAO.findById(createdProd.getId());
        Assert.assertFalse("Product should now be inactive", deactivated.isActive());

        // Admin toggles active to true
        boolean toggledOn = productDAO.toggleProductActive(createdProd.getId(), true);
        Assert.assertTrue(toggledOn);
        Product reactivated = productDAO.findById(createdProd.getId());
        Assert.assertTrue("Product should now be active", reactivated.isActive());

        // Platform metrics should be accessible
        BigDecimal platformRev = orderDAO.getPlatformTotalRevenue();
        Assert.assertNotNull("Platform revenue should be queryable", platformRev);
        int platformOrders = orderDAO.getPlatformTotalOrders();
        Assert.assertTrue("Platform orders count should be non-negative", platformOrders >= 0);
    }
}
