package com.rashik.rashikmart.config;

import com.rashik.rashikmart.dao.UserDAO;
import com.rashik.rashikmart.model.User;

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import javax.servlet.annotation.WebListener;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

@WebListener
public class DatabaseContextListener implements ServletContextListener {

    @Override
    public void contextInitialized(ServletContextEvent sce) {

        String usersTable = """
                CREATE TABLE IF NOT EXISTS users (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    email VARCHAR(150) NOT NULL UNIQUE,
                    password VARCHAR(255) NOT NULL,
                    role VARCHAR(30) NOT NULL
                )
                """;

        String productsTable = """
                CREATE TABLE IF NOT EXISTS products (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    seller_id INT NOT NULL,
                    name VARCHAR(150) NOT NULL,
                    description VARCHAR(1000),
                    category VARCHAR(100) NOT NULL,
                    price DECIMAL(12,2) NOT NULL,
                    quantity INT NOT NULL,
                    image_url VARCHAR(255) DEFAULT 'default-product.svg',
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_products_seller
                        FOREIGN KEY (seller_id)
                        REFERENCES users(id)
                )
                """;

        String cartTable = """
                CREATE TABLE IF NOT EXISTS cart (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    buyer_id INT NOT NULL UNIQUE,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_cart_buyer
                        FOREIGN KEY (buyer_id)
                        REFERENCES users(id)
                )
                """;

        String cartItemsTable = """
                CREATE TABLE IF NOT EXISTS cart_items (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cart_id INT NOT NULL,
                    product_id INT NOT NULL,
                    quantity INT NOT NULL,
                    CONSTRAINT fk_cart_items_cart
                        FOREIGN KEY (cart_id)
                        REFERENCES cart(id) ON DELETE CASCADE,
                    CONSTRAINT fk_cart_items_product
                        FOREIGN KEY (product_id)
                        REFERENCES products(id) ON DELETE CASCADE,
                    CONSTRAINT uq_cart_product
                        UNIQUE (cart_id, product_id)
                )
                """;

        String ordersTable = """
                CREATE TABLE IF NOT EXISTS orders (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    buyer_id INT NOT NULL,
                    total_amount DECIMAL(12,2) NOT NULL,
                    status VARCHAR(50) DEFAULT 'CONFIRMED',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_orders_buyer
                        FOREIGN KEY (buyer_id)
                        REFERENCES users(id)
                )
                """;

        String orderItemsTable = """
                CREATE TABLE IF NOT EXISTS order_items (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    order_id INT NOT NULL,
                    product_id INT NOT NULL,
                    quantity INT NOT NULL,
                    price DECIMAL(12,2) NOT NULL,
                    CONSTRAINT fk_order_items_order
                        FOREIGN KEY (order_id)
                        REFERENCES orders(id) ON DELETE CASCADE,
                    CONSTRAINT fk_order_items_product
                        FOREIGN KEY (product_id)
                        REFERENCES products(id)
                )
                """;

        String reviewsTable = """
                CREATE TABLE IF NOT EXISTS reviews (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    product_id INT NOT NULL,
                    buyer_id INT NOT NULL,
                    rating INT NOT NULL,
                    review_text VARCHAR(500),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_reviews_product
                        FOREIGN KEY (product_id)
                        REFERENCES products(id) ON DELETE CASCADE,
                    CONSTRAINT fk_reviews_buyer
                        FOREIGN KEY (buyer_id)
                        REFERENCES users(id),
                    CONSTRAINT uq_reviews_product_buyer
                        UNIQUE (product_id, buyer_id)
                )
                """;

        String alterProductsImage = """
                ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url VARCHAR(255) DEFAULT 'default-product.svg'
                """;

        String alterProductsActive = """
                ALTER TABLE products ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE
                """;

        try (
                Connection connection =
                        DatabaseConfig.getDataSource().getConnection()
        ) {

            String[] ddlStatements = {
                    usersTable,
                    productsTable,
                    alterProductsImage,
                    alterProductsActive,
                    cartTable,
                    cartItemsTable,
                    ordersTable,
                    orderItemsTable,
                    reviewsTable
            };

            for (String sql : ddlStatements) {
                try (java.sql.PreparedStatement statement = connection.prepareStatement(sql)) {
                    statement.execute();
                } catch (SQLException ignored) {
                }
            }

            // Ensure images/products directory exists
            String productsImgPath = sce.getServletContext().getRealPath("/images/products");
            if (productsImgPath != null) {
                File dir = new File(productsImgPath);
                if (!dir.exists()) {
                    dir.mkdirs();
                }
            }

            // Seed default admin account if not exists
            UserDAO userDAO = new UserDAO();
            if (userDAO.findByEmail("admin@rashikmart.com") == null) {
                userDAO.registerUser(new User(
                        "System Administrator",
                        "admin@rashikmart.com",
                        "admin123",
                        "ADMIN"
                ));
                System.out.println("Default admin user created: admin@rashikmart.com");
            }

            System.out.println("=================================");
            System.out.println("H2 DATABASE INITIALIZED");
            System.out.println("Users table ready");
            System.out.println("Products table ready");
            System.out.println("Cart & Cart Items tables ready");
            System.out.println("Orders & Order Items tables ready");
            System.out.println("Reviews table ready");
            System.out.println("=================================");

        } catch (SQLException e) {

            throw new RuntimeException(
                    "Database initialization failed",
                    e
            );
        }
    }

    @Override
    public void contextDestroyed(ServletContextEvent sce) {

        if (DatabaseConfig.getDataSource() != null) {

            DatabaseConfig
                    .getDataSource()
                    .close();

            System.out.println(
                    "HikariCP connection pool closed."
            );
        }
    }
}