package com.rashik.rashikmart.config;

import com.rashik.rashikmart.dao.UserDAO;
import com.rashik.rashikmart.model.User;

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;

import java.io.File;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class DatabaseContextListener implements ServletContextListener {

    @Override
    public void contextInitialized(ServletContextEvent sce) {

        String usersTable = """
                CREATE TABLE IF NOT EXISTS users (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    email VARCHAR(150) NOT NULL UNIQUE,
                    password VARCHAR(255) NOT NULL,
                    role VARCHAR(30) NOT NULL
                )
                """;

        String productsTable = """
                CREATE TABLE IF NOT EXISTS products (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    seller_id INT NOT NULL,
                    name VARCHAR(150) NOT NULL,
                    description VARCHAR(1000),
                    category VARCHAR(100) NOT NULL,
                    price DECIMAL(12,2) NOT NULL,
                    quantity INT NOT NULL,
                    image_url VARCHAR(255) DEFAULT 'default-product.svg',
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_products_seller
                        FOREIGN KEY (seller_id)
                        REFERENCES users(id)
                )
                """;

        String cartTable = """
                CREATE TABLE IF NOT EXISTS cart (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    buyer_id INT NOT NULL UNIQUE,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_cart_buyer
                        FOREIGN KEY (buyer_id)
                        REFERENCES users(id)
                )
                """;

        String cartItemsTable = """
                CREATE TABLE IF NOT EXISTS cart_items (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cart_id INT NOT NULL,
                    product_id INT NOT NULL,
                    quantity INT NOT NULL,
                    CONSTRAINT fk_cart_items_cart
                        FOREIGN KEY (cart_id)
                        REFERENCES cart(id) ON DELETE CASCADE,
                    CONSTRAINT fk_cart_items_product
                        FOREIGN KEY (product_id)
                        REFERENCES products(id) ON DELETE CASCADE,
                    CONSTRAINT uq_cart_product
                        UNIQUE (cart_id, product_id)
                )
                """;

        String ordersTable = """
                CREATE TABLE IF NOT EXISTS orders (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    buyer_id INT NOT NULL,
                    total_amount DECIMAL(12,2) NOT NULL,
                    status VARCHAR(50) DEFAULT 'CONFIRMED',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_orders_buyer
                        FOREIGN KEY (buyer_id)
                        REFERENCES users(id)
                )
                """;

        String orderItemsTable = """
                CREATE TABLE IF NOT EXISTS order_items (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    order_id INT NOT NULL,
                    product_id INT NOT NULL,
                    quantity INT NOT NULL,
                    price DECIMAL(12,2) NOT NULL,
                    CONSTRAINT fk_order_items_order
                        FOREIGN KEY (order_id)
                        REFERENCES orders(id) ON DELETE CASCADE,
                    CONSTRAINT fk_order_items_product
                        FOREIGN KEY (product_id)
                        REFERENCES products(id)
                )
                """;

        String reviewsTable = """
                CREATE TABLE IF NOT EXISTS reviews (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    product_id INT NOT NULL,
                    buyer_id INT NOT NULL,
                    rating INT NOT NULL,
                    review_text VARCHAR(500),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_reviews_product
                        FOREIGN KEY (product_id)
                        REFERENCES products(id) ON DELETE CASCADE,
                    CONSTRAINT fk_reviews_buyer
                        FOREIGN KEY (buyer_id)
                        REFERENCES users(id),
                    CONSTRAINT uq_reviews_product_buyer
                        UNIQUE (product_id, buyer_id)
                )
                """;

        String alterProductsImage = """
                ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url VARCHAR(255) DEFAULT 'default-product.svg'
                """;

        String alterProductsActive = """
                ALTER TABLE products ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE
                """;

        try (
                Connection connection =
                        DatabaseConfig.getDataSource().getConnection()
        ) {

            String[] ddlStatements = {
                    usersTable,
                    productsTable,
                    alterProductsImage,
                    alterProductsActive,
                    cartTable,
                    cartItemsTable,
                    ordersTable,
                    orderItemsTable,
                    reviewsTable
            };

            for (String sql : ddlStatements) {
                try (java.sql.PreparedStatement statement = connection.prepareStatement(sql)) {
                    statement.execute();
                } catch (SQLException ignored) {
                }
            }

            // Ensure the external product-images upload directory exists
            File uploadDir =
                    new File(
                            DatabaseConfig.getUploadDir()
                    );

            if (!uploadDir.exists()
                    && !uploadDir.mkdirs()) {

                System.err.println(
                        "WARNING: Could not create product image upload directory: "
                                + uploadDir.getAbsolutePath()
                );
            }

            // Seed default admin account if not exists
            UserDAO userDAO = new UserDAO();
            if (userDAO.findByEmail("admin@rashikmart.com") == null) {
                userDAO.registerUser(new User(
                        "System Administrator",
                        "admin@rashikmart.com",
                        "admin123",
                        "ADMIN"
                ));
                System.out.println("Default admin user created: admin@rashikmart.com");
            }

            // Seed the demo seller and product catalog (idempotent).
            seedCatalog(connection);

            System.out.println("=================================");
            System.out.println("H2 DATABASE INITIALIZED");
            System.out.println("Users table ready");
            System.out.println("Products table ready");
            System.out.println("Cart & Cart Items tables ready");
            System.out.println("Orders & Order Items tables ready");
            System.out.println("Reviews table ready");
            System.out.println("=================================");

        } catch (SQLException e) {

            throw new RuntimeException(
                    "Database initialization failed",
                    e
            );
        }
    }

    @Override
    public void contextDestroyed(ServletContextEvent sce) {

        if (DatabaseConfig.getDataSource() != null) {

            DatabaseConfig
                    .getDataSource()
                    .close();

            System.out.println(
                    "HikariCP connection pool closed."
            );
        }
    }

    /**
     * Applies the bundled catalog seed (seed_catalog.sql, identical to the
     * committed database/seed.sql export) using H2's RunScript, reusing the
     * same pooled connection.
     *
     * The seed only runs on a FRESH database: if the products table already
     * contains rows, the seed is skipped entirely so existing data is never
     * modified and no duplicate products/seller are ever created on restart.
     * As an extra safety net the script itself is also fully idempotent.
     */
    private void seedCatalog(Connection connection) {

        try (PreparedStatement check =
                     connection.prepareStatement(
                             "SELECT COUNT(*) FROM products"
                     )) {

            try (ResultSet resultSet = check.executeQuery()) {

                if (resultSet.next()
                        && resultSet.getInt(1) > 0) {

                    System.out.println(
                            "Catalog seed skipped: "
                                    + "products already present ("
                                    + resultSet.getInt(1)
                                    + " existing)."
                    );

                    return;
                }
            }

        } catch (SQLException e) {

            System.err.println(
                    "Catalog seed check failed: "
                            + e.getMessage()
            );
        }

        String resource = "seed_catalog.sql";

        try (InputStream in =
                     getClass().getClassLoader()
                             .getResourceAsStream(resource)) {

            if (in == null) {

                System.out.println(
                        "Catalog seed skipped: " + resource
                                + " not found on classpath"
                );

                return;
            }

            try (InputStreamReader reader =
                         new InputStreamReader(
                                 in,
                                 StandardCharsets.UTF_8
                         )) {

                org.h2.tools.RunScript.execute(
                        connection,
                        reader
                );
            }

            System.out.println(
                    "Catalog seed applied "
                            + "(seller + product catalog)."
            );

        } catch (Exception e) {

            System.err.println(
                    "Catalog seed failed: "
                            + e.getMessage()
            );

            e.printStackTrace();
        }
    }
}