package com.rashik.rashikmart.config;

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import javax.servlet.annotation.WebListener;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

@WebListener
public class DatabaseContextListener implements ServletContextListener {

    @Override
    public void contextInitialized(ServletContextEvent sce) {

        String usersTable = """
                CREATE TABLE IF NOT EXISTS users (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    email VARCHAR(150) NOT NULL UNIQUE,
                    password VARCHAR(255) NOT NULL,
                    role VARCHAR(30) NOT NULL
                )
                """;

        String productsTable = """
                CREATE TABLE IF NOT EXISTS products (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    seller_id INT NOT NULL,
                    name VARCHAR(150) NOT NULL,
                    description VARCHAR(1000),
                    category VARCHAR(100) NOT NULL,
                    price DECIMAL(12,2) NOT NULL,
                    quantity INT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_products_seller
                        FOREIGN KEY (seller_id)
                        REFERENCES users(id)
                )
                """;

        try (
                Connection connection =
                        DatabaseConfig.getDataSource().getConnection();

                Statement statement =
                        connection.createStatement()
        ) {

            statement.executeUpdate(usersTable);
            statement.executeUpdate(productsTable);

            System.out.println("=================================");
            System.out.println("H2 DATABASE INITIALIZED");
            System.out.println("Users table ready");
            System.out.println("Products table ready");
            System.out.println("=================================");

        } catch (SQLException e) {

            throw new RuntimeException(
                    "Database initialization failed",
                    e
            );
        }
    }

    @Override
    public void contextDestroyed(ServletContextEvent sce) {

        if (DatabaseConfig.getDataSource() != null) {

            DatabaseConfig
                    .getDataSource()
                    .close();

            System.out.println(
                    "HikariCP connection pool closed."
            );
        }
    }
}