package com.rashik.rashikmart.security;

import com.rashik.rashikmart.config.DatabaseConfig;
import com.rashik.rashikmart.dao.ProductDAO;
import com.rashik.rashikmart.dao.UserDAO;
import com.rashik.rashikmart.model.User;
import com.rashik.rashikmart.util.HtmlUtil;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import java.sql.Connection;
import java.sql.Statement;

public class SecurityTest {

    private static UserDAO userDAO;
    private static ProductDAO productDAO;

    @BeforeClass
    public static void setUp() throws Exception {
        userDAO = new UserDAO();
        productDAO = new ProductDAO();

        try (Connection conn = DatabaseConfig.getDataSource().getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS users (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        email VARCHAR(150) NOT NULL UNIQUE,
                        password VARCHAR(255) NOT NULL,
                        role VARCHAR(30) NOT NULL
                    );
                    """);
        }
    }

    @Test
    public void testSqlInjectionPayloadsFailInUserLookup() {
        // Classic SQL injection attempts that would return a row if string concatenation were used:
        String[] payloads = {
                "' OR '1'='1",
                "' OR 1=1 --",
                "admin' --",
                "' UNION SELECT id, name, email, password, role FROM users --"
        };

        for (String payload : payloads) {
            User user = userDAO.findByEmail(payload);
            Assert.assertNull("SQL injection payload '" + payload + "' must return null via PreparedStatement", user);
        }
    }

    @Test
    public void testHtmlUtilEscapesXssPayloads() {
        // Test script injection
        String scriptPayload = "<script>alert('XSS')</script>";
        String escapedScript = HtmlUtil.escape(scriptPayload);
        Assert.assertFalse("Escaped string must not contain raw '<script>'", escapedScript.contains("<script>"));
        Assert.assertEquals("&lt;script&gt;alert(&#x27;XSS&#x27;)&lt;/script&gt;", escapedScript);

        // Test img onerror injection
        String imgPayload = "<img src=x onerror=alert(1)>";
        String escapedImg = HtmlUtil.escape(imgPayload);
        Assert.assertFalse("Escaped string must not contain raw '<img'", escapedImg.contains("<img"));
        Assert.assertEquals("&lt;img src=x onerror=alert(1)&gt;", escapedImg);

        // Test quote and ampersand injection
        String quotePayload = "\" onmouseover=\"alert('xss')\" & '";
        String escapedQuotes = HtmlUtil.escape(quotePayload);
        Assert.assertEquals("&quot; onmouseover=&quot;alert(&#x27;xss&#x27;)&quot; &amp; &#x27;", escapedQuotes);

        // Test null handling
        Assert.assertEquals("", HtmlUtil.escape(null));
    }

    @Test
    public void testBcryptHashStrength() {
        String password = "SuperSecretPassword2026!";
        User user = new User("Strength Test", "strength@test.com", password, "BUYER");
        userDAO.registerUser(user);

        User saved = userDAO.findByEmail("strength@test.com");
        Assert.assertNotNull(saved);

        // BCrypt format: $2a$12$... or $2b$12$... (cost factor 12)
        Assert.assertTrue("BCrypt hash must start with $2a$ or $2b$",
                saved.getPassword().startsWith("$2a$") || saved.getPassword().startsWith("$2b$"));
        Assert.assertTrue("BCrypt hash must be 60 characters in length", saved.getPassword().length() == 60);

        // Password should verify
        Assert.assertTrue(userDAO.verifyPassword(password, saved.getPassword()));
        // Plain text should never equal hash
        Assert.assertNotEquals(password, saved.getPassword());
    }
}
